services:

  oj-judge:
    build:
      context: ./JudgeServer-master
      dockerfile: Dockerfile
    image: crpi-bf3kcemfp45x9kin.cn-guangzhou.personal.cr.aliyuncs.com/kiffy-oj/judge:v2.0

  oj-backend:
    build:
      context: ./OnlineJudge-master
      dockerfile: Dockerfile
    image: crpi-bf3kcemfp45x9kin.cn-guangzhou.personal.cr.aliyuncs.com/kiffy-oj/backend:v2.0

  oj-frontend:
    build:
      context: ./OnlineJudgeFE-master
      dockerfile: deploy/Dockerfile
    image: crpi-bf3kcemfp45x9kin.cn-guangzhou.personal.cr.aliyuncs.com/kiffy-oj/frontend:v2.0
